[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JetReconstruction = "44e8cb2c-dfab-4825-9c70-d4808a591196"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"

[sources]
JetReconstruction = {path = ".."}
