name = "JetReconstruction"
uuid = "44e8cb2c-dfab-4825-9c70-d4808a591196"
authors = ["Atell Krasnopolski <delta_atell@protonmail.com>", "Graeme A Stewart <graeme.andrew.stewart@cern.ch", "Philippe Gras <philippe.gras@cern.ch>"]
version = "0.5.0-dev"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
LorentzVectorHEP = "f612022c-142a-473f-8cfd-a09cf3793c6c"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
EDM4hep = "eb32b910-dde9-4347-8fce-cd6be3498f0c"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ONNXRunTime = "e034b28e-924e-41b2-b98f-d2bbeb830c6a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"

[extensions]
EDM4hepJets = "EDM4hep"
JetVisualisation = "Makie"
JetFlavourTagging = ["EDM4hep", "ONNXRunTime", "JSON", "PhysicalConstants"]

[compat]
Accessors = "0.1.36"
Aqua = "0.8"
CodecZlib = "0.7"
CodecZstd = "0.8"
EDM4hep = "0.4.0"
EnumX = "1.0.4"
JSON = "0.21"
Logging = "1.9"
LoopVectorization = "0.12.170"
LorentzVectorHEP = "0.1.6"
Makie = "0.20, 0.21, 0.22, 0.23, 0.24"
MuladdMacro = "0.2.4"
Random = "1.9"
Statistics = "1.9"
ONNXRunTime = "1.3.1"
StructArrays = "0.6.18, 0.7"
Test = "1.9"
julia = "1.9"
PhysicalConstants = "0.2.4"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "JSON", "Random"]
