[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JetReconstruction = "44e8cb2c-dfab-4825-9c70-d4808a591196"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"

[sources]
JetReconstruction = {path = ".."}

[compat]
JetReconstruction = "0.4"
PackageCompiler = "2"
