[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JetReconstruction = "44e8cb2c-dfab-4825-9c70-d4808a591196"
LorentzVectorHEP = "f612022c-142a-473f-8cfd-a09cf3793c6c"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"

[sources]
JetReconstruction = {path = ".."}
